### ISSUE TITLE
npm install statsd results in many errors with node 0.1.2.7

### ISSUE THREAD

**Issue by smartmouse** [etsy/statsd#531]
platform x-linux

$ npm install statsd
-
> node-syslog@1.1.7 install /home/nodebot/testIy/node_modules/st                            atsd/node_modules/node-syslog
> node-gyp rebuild

make: Entering directory `/home/nodebot/testIy/node_modules/stat                            sd/node_modules/node-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:1:0:
../node-syslog.h:22:45: error: ‘Arguments’ in namespace ‘v8’ does                             not name a type
  static v8::Handle<v8::Value> init   (const v8::Arguments& args)                            ;
                                             ^
../node-syslog.h:22:60: error: ISO C++ forbids declaration of ‘ar                            gs’ with no type [-fpermissive]
  static v8::Handle<v8::Value> init   (const v8::Arguments& args)                            ;
                                                            ^
../node-syslog.h:23:42: error: ‘Arguments’ in namespace ‘v8’ does                             not name a type
  static v8::Handle<v8::Value> log (const v8::Arguments& args);
                                          ^
../node-syslog.h:23:57: error: ISO C++ forbids declaration of ‘ar                            gs’ with no type [-fpermissive]
  static v8::Handle<v8::Value> log (const v8::Arguments& args);
                                                         ^
../node-syslog.h:24:46: error: ‘Arguments’ in namespace ‘v8’ does                             not name a type
  static v8::Handle<v8::Value> setMask (const v8::Arguments& args                            );
                                              ^
../node-syslog.h:24:61: error: ISO C++ forbids declaration of ‘ar                            gs’ with no type [-fpermissive]
  static v8::Handle<v8::Value> setMask (const v8::Arguments& args                            );
                                                             ^
../node-syslog.h:25:46: error: ‘Arguments’ in namespace ‘v8’ does                             not name a type
  static v8::Handle<v8::Value> destroy (const v8::Arguments& args                            );
                                              ^
../node-syslog.h:25:61: error: ISO C++ forbids declaration of ‘ar                            gs’ with no type [-fpermissive]
  static v8::Handle<v8::Value> destroy (const v8::Arguments& args                            );
                                                             ^
../syslog.cc: In static member function ‘static void node::Syslog                            ::Initialize(v8::Handle<v8::Object>)’:
../syslog.cc:13:52: error: no matching function for call to ‘v8::                            FunctionTemplate::New()’
  Local<FunctionTemplate> t = FunctionTemplate::New();
                                                    ^
../syslog.cc:13:52: note: candidate is:
In file included from /home/nodebot/.node-gyp/0.12.7/src/node.h:6                            1:0,
                 from ../node-syslog.h:4,
                 from ../syslog.cc:1:
/home/nodebot/.node-gyp/0.12.7/deps/v8/include/v8.h:3455:34: note                            : static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::Ne                            w(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::                            Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/nodebot/.node-gyp/0.12.7/deps/v8/include/v8.h:3455:34: note                            :   candidate expects 5 arguments, 0 provided
../syslog.cc:14:60: error: no matching function for call to ‘v8::                            Persistent<v8::FunctionTemplate>::New(v8::Local<v8::FunctionTempl                            ate>&)’
  constructor_template = Persistent<FunctionTemplate>::New(t);
                                                            ^
../syslog.cc:14:60: note: candidate is:
In file included from /home/nodebot/.node-gyp/0.12.7/src/node.h:6                            1:0,
                 from ../node-syslog.h:4,
                 from ../syslog.cc:1:
/home/nodebot/.node-gyp/0.12.7/deps/v8/include/v8.h:5798:4: note:                             static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T =                             v8::FunctionTemplate]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/home/nodebot/.node-gyp/0.12.7/deps/v8/include/v8.h:5798:4: note:                               candidate expects 2 arguments, 1 provided
../syslog.cc:15:22: error: base operand of ‘->’ has non-pointer t                            ype ‘v8::Persistent<v8::FunctionTemplate>’
  constructor_template->InstanceTemplate()->SetInternalFieldCount                            (1);
                      ^
../syslog.cc:16:22: error: base operand of ‘->’ has non-pointer t                            ype ‘v8::Persistent<v8::FunctionTemplate>’
  constructor_template->SetClassName(String::NewSymbol("Syslog"))                            ;
                      ^
../syslog.cc:16:37: error: ‘NewSymbol’ is not a member of ‘v8::St                            ring’
  constructor_template->SetClassName(String::NewSymbol("Syslog"))                            ;
                                     ^
../syslog.cc:19:60: error: no matching function for call to ‘NODE                            _SET_METHOD(v8::Persistent<v8::FunctionTemplate>&, const char [5]                            , v8::Handle<v8::Value> (&)(const int&))’
  NODE_SET_METHOD(constructor_template, "init", Syslog::init);
                                                            ^
../syslog.cc:19:60: note: candidate is:
In file included from ../node-syslog.h:4:0,
                 from ../syslog.cc:1:
/home/nodebot/.node-gyp/0.12.7/src/node.h:228:13: note: template<                            class TypeName> void node::NODE_SET_METHOD(const TypeName&, const                             char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/nodebot/.node-gyp/0.12.7/src/node.h:228:13: note:   templat                            e argument deduction/substitution failed:
../syslog.cc:19:60: note:   cannot convert ‘node::Syslog::init’ (                            type ‘v8::Handle<v8::Value>(const int&)’) to type ‘v8::FunctionCa                            llback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)                             ’
  NODE_SET_METHOD(constructor_template, "init", Syslog::init);
                                                            ^
../syslog.cc:20:58: error: no matching function for call to ‘NODE                            _SET_METHOD(v8::Persistent<v8::FunctionTemplate>&, const char [4]                            , v8::Handle<v8::Value> (&)(const int&))’
  NODE_SET_METHOD(constructor_template, "log", Syslog::log);
                                                          ^
../syslog.cc:20:58: note: candidate is:
In file included from ../node-syslog.h:4:0,
                 from ../syslog.cc:1:
/home/nodebot/.node-gyp/0.12.7/src/node.h:228:13: note: template<                            class TypeName> void node::NODE_SET_METHOD(const TypeName&, const                             char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/nodebot/.node-gyp/0.12.7/src/node.h:228:13: note:   templat                            e argument deduction/substitution failed:
../syslog.cc:20:58: note:   cannot convert ‘node::Syslog::log’ (t                            ype ‘v8::Handle<v8::Value>(const int&)’) to type ‘v8::FunctionCal                            lback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
  NODE_SET_METHOD(constructor_template, "log", Syslog::log);
                                                          ^
../syslog.cc:21:66: error: no matching function for call to ‘NODE                            _SET_METHOD(v8::Persistent<v8::FunctionTemplate>&, const char [8]                            , v8::Handle<v8::Value> (&)(const int&))’
  NODE_SET_METHOD(constructor_template, "setMask", Syslog::setMas                            k);
                                                                                              ^
../syslog.cc:21:66: note: candidate is:
In file included from ../node-syslog.h:4:0,
                 from ../syslog.cc:1:
/home/nodebot/.node-gyp/0.12.7/src/node.h:228:13: note: template<                            class TypeName> void node::NODE_SET_METHOD(const TypeName&, const                             char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/nodebot/.node-gyp/0.12.7/src/node.h:228:13: note:   templat                            e argument deduction/substitution failed:
../syslog.cc:21:66: note:   cannot convert ‘node::Syslog::setMas                             ’ (type ‘v8::Handle<v8::Value>(const int&)’) to type ‘v8::Functio                            nCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>                            &)}’
  NODE_SET_METHOD(constructor_template, "setMask", Syslog::setMas                            k);
                                                                                              ^
../syslog.cc:22:64: error: no matching function for call to ‘NODE                            _SET_METHOD(v8::Persistent<v8::FunctionTemplate>&, const char [6]                            , v8::Handle<v8::Value> (&)(const int&))’
  NODE_SET_METHOD(constructor_template, "close", Syslog::destroy)                            ;

**Comment by mrtazz** [comment]
Thanks for submitting an issue! This problem was already fixed in https://github.com/etsy/statsd/commit/4a555df3c4f8abde146d154408f856423b049f1f but we have yet to upload the fix to npm. We are looking into being able to publish a bugfix release for this, so I'm closing this issue for now. If this is blocking you, you should be able to use the master branch and `npm install` should work there.

**Comment by mhiller** [comment]
FYI this is still an issue in npm

**Comment by hernandesbsousa** [comment]
It looks like this issue is still going on, is there anything that can be done to help in order to get this fixed?

**Comment by kylev** [comment]
Looks like schamane/node-syslog@4ac4dc indicates the author of node-syslog has abandoned it.

**Comment by pathzzrd** [comment]
as an update:
we've merged in #565 and are looking into cutting a new release on npm within the next week or two. we'll be more diligent about this in the future. onward!
